services:
  - type: web
    name: main
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
