apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
schemaVersion: 1.1
endpoints:
  - name: email-validation-api
    displayName: Email Validation API
    service:
      basePath: /validate_email/
      port: 8000
    type: REST
    networkVisibilities:
      - Public
    schemaFilePath: .choreo/openapi.yaml
